---
title: "GoalOrientation"
output: html_document
---

```{r}
dat<-read.csv("Goal Orientation answersfinal.csv")
```


```{r}
str(dat)
```


```{r}
dat$Gender<-as.factor(dat$Gender)
dat$Condition<-as.factor(dat$Condition)
```

```{r}
summary(aov(Result~Condition*Gender, data=dat))
```

```{r}
library(ggplot2)
library(gplots)
library(dplyr)
```


```{r}
temp<-dat%>%group_by(Condition,Gender)%>%
  summarize(means=mean(Result),
            sems=sd(Result)/sqrt(length(n)))
```

```{r}
f<-ggplot(temp, aes(x=Condition,
                    y=means,
                    group=Gender,
                    color=Gender))+
  geom_line(size=1)+
  geom_point(size=2)+
  scale_color_manual(values=c("darkgreen","red"),
                     name="Gender",
                     breaks=c("Male","Female"),
                     labels=c("Male", "Female"))+
  geom_errorbar(aes(ymax=means+sems, ymin=means-sems),width=.2)+
  ggtitle("Goal Orientation Effect on Gender")+
  labs(x="Goal Orientation",y="Survey Score")+
  theme(plot.title=element_text(size=15,face="bold",vjust=.5))+
  theme(axis.title.x=element_text(size=12,face="bold",vjust=-.25))+
  theme(axis.title.y=element_text(size=12,face="bold",vjust=1))+
  theme(axis.text.x=element_text(size=10,face="bold",color="black"))+
  theme(axis.text.y=element_text(size=10,face="bold",color="black"))+
  coord_cartesian(ylim=c(min(temp$means)-2*max(temp$sems),
                         max(temp$means)+2*max(temp$sems)))+
  theme(panel.border=element_blank(),axis.line=element_line())+
  theme(panel.grid.major.x=element_blank())+
  theme(panel.grid.major.y=element_line(color="darkgrey"))+
  theme(panel.grid.minor.y=element_blank())+
  theme(legend.position=c(.4,.76))+
  theme(legend.background=element_blank())+
  theme(legend.background=element_rect(color="black"))+
  theme(legend.title=element_blank())+
  theme(legend.title=element_text(size=12))+
  theme(legend.title.align=.5)+
  theme(legend.text=element_text(size=10,face="bold"))
f

f<-ggplot(temp, aes(x=Condition,
                    y=means,
                    fill=Gender))+
  geom_bar(stat="identity",position=position_dodge())+
  scale_fill_manual(values=c("darkgreen","red"),
                     name="Gender",
                     breaks=c("Male", "Female"),
                     labels=c("Male", "Female"))+
  geom_errorbar(aes(ymax=means+sems,
                    ymin=means-sems),
                width=.2,
                position=position_dodge(.9))+
  ggtitle("Goal Orientation Effect on Gender")+
  labs(x="Goal Orientation",y="Survey Score")+
  theme(plot.title=element_text(size=15,face="bold",vjust=.5))+
  theme(axis.title.x=element_text(size=12,face="bold",vjust=-.25))+
  theme(axis.title.y=element_text(size=12,face="bold",vjust=1))+
  theme(axis.text.x=element_text(size=10,face="bold",color="black"))+
  theme(axis.text.y=element_text(size=10,face="bold",color="black"))+
  coord_cartesian(ylim=c(min(temp$means)-2*max(temp$sems),
                         max(temp$means)+2*max(temp$sems)))+
  theme(panel.border=element_blank(),axis.line=element_line())+
  theme(panel.grid.major.x=element_blank())+
  theme(panel.grid.major.y=element_line(color="darkgrey"))+
  theme(panel.grid.minor.y=element_blank())+
  theme(legend.position=c(.4,.76))+
  theme(legend.background=element_blank())+
  theme(legend.background=element_rect(color="black"))+
  theme(legend.title=element_blank())+
  theme(legend.title=element_text(size=12))+
  theme(legend.title.align=.5)+
  theme(legend.text=element_text(size=10,face="bold"))
f
```