## Example 6

<!--
Set the working directory.
No Rchunk is needed to accomplish this.
-->

<!--
Read in the homework6.csv data. For each of the following steps you
should preface your R commands with some plain English explanation.
The fabricated data are supposed to approximate how people perform
in different types of visual searches. Specifically, we're 
comparing performance in feature searches (e.g. looking for a red
X among green Xs) and conjunction searches (e.g. looking for a red
X among green Xs and red Os). We're also looking at how the number
of distractors within the search display effect our data.
-->

```{r}
dat<-read.csv("homework6.csv")
```

<!--
Check the structure of the data and change any variables that should
be factor variables into factor variables
-->

```{r}
str(dat)
```

<!--
Perform a one-way between-subjects ANOVA examining for effects of 
the the number of distractors for the conjunction searches only.
Also create a line graph to help you interpret the results of your
analysis.
-->

```{r}
dat$type<-as.factor(dat$type)
dat$subject<-as.factor(dat$subject)
dat$subject2<-as.factor(dat$subject2)
```

<!--
Perform a one-way within subjects ANOVA on the same data you analyzed
earlier. Tip: use subject as the subjects variable for this analysis.
-->

```{r}
temp<-dat[dat$distractors=="yes",]
```

```{r}
summary(aov(rt~type, data=temp))
```

```{r}
library(ggplot2)
library(gplots)
library(dplyr)

temp<-temp%>%group_by(type)%>%
  summarize(means=mean(rt),
            sems=sd(rt)/sqrt(length(rt)))

f<-ggplot(temp, aes(x=as.factor(position),
                    y=means,
                    group=1))+
  geom_line(size=1)+
  geom_point(size=2)+
  geom_errorbar(aes(ymax=means+sems,
                    ymin=means-sems),
                width=.2)+
  ggtitle("Serial Position Effect")+
  labs(x="List type",y="rt Recalled")+
  theme(plot.title=element_text(size=15,face="bold",vjust=.5))+
  theme(axis.title.x=element_text(size=12,face="bold",vjust=-.25))+
  theme(axis.title.y=element_text(size=12,face="bold",vjust=1))+
  theme(axis.text.x=element_text(size=10,face="bold",color="black"))+
  theme(axis.text.y=element_text(size=10,face="bold",color="black"))+
  coord_cartesian(ylim=c(min(temp$means)-2*max(temp$sems),
                         max(temp$means)+2*max(temp$sems)))+
  theme(panel.border=element_blank(),axis.line=element_line())+
  theme(panel.grid.major.x=element_blank())+
  theme(panel.grid.major.y=element_line(color="darkgrey"))+
  theme(panel.grid.minor.y=element_blank())
f
```
<!--
Perform a between-subjects ANOVA examining for the effects of and
interactions between the number of distractors and the search type.
Make sure to interpret your results.
-->

<!--
Create a line graph and a grouped bar graph to help us interpret
the results of the previous analyses. Include error bars in your
figures.
-->

<!--
Interpret the statistical results in light of the figures.
-->


<!--
Perform a within-subjects two-way ANOVA examining for the effects
of and interactions between number of distractors and search type.
Tip: use subject as the subject's variable for this analysis.
Interpret the results of the analysis based on the statistical
results and your earlier figures.
-->



<!--
Finally conduct and interpret the results of a mixed ANOVA in which
number of distractors varies within subjects and the type of search
varies between subjects. Make sure to interpret your results. Tip:
use subject2 as your subject's variable for this analysis.
-->
